#!/bin/bash

#for i in $(pip freeze | perl -ne '/^(robotpy.*?)==/ and print "$1\n"'); do
for i in $(pip freeze | perl -ne '/^(\S+?)==/ and print "$1\n"'); do
  pip index --pre versions $i 2>&1 | perl -ne '
    /'$i' \((\S+)\)/ and $latest = $1;
    /INSTALLED: (\S+)/ or next;
    $inst = $1;
    print "'$i': $inst -> $latest\n" if $inst ne $latest;
    $latest = "";
  '
done

